// loaders.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import {MD5Hash} from '@loaders.gl/crypto';
import {ZipWriter} from './zip-writer';

/** Already encoded resources. Inputs must remain unchanged while packaging. */
export type IndexedZipFiles = Readonly<Record<string, ArrayBuffer | Blob>>;

/** Configuration for a deterministic STORE ZIP32 with a final MD5 path/offset index. */
export interface IndexedZipOptions {
  /** Canonical ASCII, nonnumeric name for the generated final index entry. */
  readonly indexPath: string;
  /** Maximum final archive bytes, including headers/index; not a peak-memory limit. */
  readonly maxArchiveBytes: number;
  /** Hash lowercase paths for SLPK; retain case-sensitive paths for 3TZ by default. */
  readonly lowercasePaths?: boolean;
  /** Cooperative cancellation between resource reads and entry encodes; not an interrupt for either. */
  readonly signal?: AbortSignal;
}

/** Largest supported archive, below the ZIP64 sentinel. */
const MAX_ARCHIVE_BYTES = 0xfffffffe;

/**
 * Encodes a bounded, deterministic indexed ZIP32 from immutable ArrayBuffers or Blobs.
 * Validates/measures all entries before reading Blobs; hashes canonical ASCII resource paths.
 * Serializes one entry at a time into the final buffer, releasing each temporary Blob read.
 * Uses populated local headers, no compression/descriptors/comments, and a fixed timestamp.
 * Cancellation is checked between reads/encodes; use worker termination to interrupt active work.
 * @param files - Already authored resources, excluding the index generated by this encoder.
 * @param options - Index naming/hash profile and maximum complete archive size.
 * @returns ZIP bytes with the final 24-byte-per-resource MD5/offset index.
 */
export async function encodeIndexedZip(
  files: IndexedZipFiles,
  options: IndexedZipOptions
): Promise<ArrayBuffer> {
  const {maxArchiveBytes, indexPath, lowercasePaths = false, signal} = options;
  signal?.throwIfAborted();
  validatePath(indexPath);
  if (/^\d+$/.test(indexPath)) {
    throw new TypeError('Indexed ZIP index path must be nonnumeric to remain the final entry');
  }
  if (!Number.isSafeInteger(maxArchiveBytes) || maxArchiveBytes < 0) {
    throw new RangeError('Indexed ZIP archive byte limit must be a non-negative safe integer');
  }
  // Integer-like object keys follow ECMAScript enumeration order in JSZip as well.
  const paths = Object.keys(
    Object.fromEntries(
      Object.keys(files)
        .sort()
        .map(path => [path, true])
    )
  );
  if (paths.length >= 0xfffe) {
    throw new RangeError('Indexed ZIP requires fewer than 65534 resource files');
  }
  const canonicalPaths = paths.map(path => (lowercasePaths ? path.toLowerCase() : path));
  if (new Set(canonicalPaths).size !== paths.length) {
    throw new TypeError('Indexed ZIP contains duplicate canonical paths');
  }
  const resources = paths.map(path => {
    validatePath(path);
    if (
      (lowercasePaths ? path.toLowerCase() : path) ===
      (lowercasePaths ? indexPath.toLowerCase() : indexPath)
    ) {
      throw new TypeError('Indexed ZIP resource uses the reserved index path');
    }
    const data = files[path];
    const byteLength =
      data instanceof ArrayBuffer
        ? (Object.getOwnPropertyDescriptor(ArrayBuffer.prototype, 'byteLength')!.get!.call(
            data
          ) as number)
        : (Object.getOwnPropertyDescriptor(Blob.prototype, 'size')!.get!.call(data) as number);
    return {path, data, byteLength};
  });
  // ZIP32: EOCD + local/central headers + both copies of each ASCII path + index payload.
  const archiveBytes = resources.reduce(
    (total, resource) => total + 76 + 2 * resource.path.length + resource.byteLength,
    22 + 76 + 2 * indexPath.length + 24 * resources.length
  );
  if (archiveBytes > Math.min(maxArchiveBytes, MAX_ARCHIVE_BYTES)) {
    throw new RangeError('Indexed ZIP archive exceeds the configured byte limit or ZIP32 capacity');
  }

  const entries: DataView[] = [];
  // Keep one final allocation and at most one resource/entry encode, rather than all Blob reads.
  const archive = new Uint8Array(archiveBytes);
  const centralDirectoryOffset = resources.reduce(
    (total, resource) => total + 30 + resource.path.length + resource.byteLength,
    30 + indexPath.length + 24 * resources.length
  );
  let centralHeaderOffset = centralDirectoryOffset;
  const hash = new MD5Hash();
  let localHeaderOffset = 0;
  for (const resource of resources) {
    signal?.throwIfAborted();
    const data =
      resource.data instanceof ArrayBuffer
        ? resource.data
        : await Blob.prototype.arrayBuffer.call(resource.data);
    signal?.throwIfAborted();
    if (data.byteLength !== resource.byteLength) {
      throw new TypeError('Indexed ZIP resource size changed during packaging');
    }
    const digest = await hash.hash(
      new TextEncoder().encode(lowercasePaths ? resource.path.toLowerCase() : resource.path).buffer,
      'hex'
    );
    const entry = new DataView(new ArrayBuffer(24));
    for (let index = 0; index < 16; index++) {
      entry.setUint8(index, Number.parseInt(digest.slice(index * 2, index * 2 + 2), 16));
    }
    entry.setBigUint64(16, BigInt(localHeaderOffset), true);
    entries.push(entry);
    signal?.throwIfAborted();
    if (data.byteLength !== resource.byteLength) {
      throw new TypeError('Indexed ZIP resource size changed during packaging');
    }
    await encodeEntry(archive, resource.path, data, localHeaderOffset, centralHeaderOffset);
    signal?.throwIfAborted();
    localHeaderOffset += 30 + resource.path.length + resource.byteLength;
    centralHeaderOffset += 46 + resource.path.length;
  }
  entries.sort(compareIndexEntries);
  const indexData = new Uint8Array(24 * entries.length);
  entries.forEach((entry, index) => indexData.set(new Uint8Array(entry.buffer), index * 24));
  signal?.throwIfAborted();
  await encodeEntry(archive, indexPath, indexData.buffer, localHeaderOffset, centralHeaderOffset);
  signal?.throwIfAborted();
  // ZIP32 end-of-central-directory record; disk numbers and comment length remain zero.
  const endOfCentralDirectory = new DataView(archive.buffer, archiveBytes - 22);
  endOfCentralDirectory.setUint32(0, 0x06054b50, true);
  endOfCentralDirectory.setUint16(8, resources.length + 1, true);
  endOfCentralDirectory.setUint16(10, resources.length + 1, true);
  endOfCentralDirectory.setUint32(12, archiveBytes - 22 - centralDirectoryOffset, true);
  endOfCentralDirectory.setUint32(16, centralDirectoryOffset, true);
  return archive.buffer;
}

/** Copies one JSZip STORE entry into the final archive and rebases its central-header offset. */
async function encodeEntry(
  archive: Uint8Array,
  path: string,
  data: ArrayBuffer,
  localHeaderOffset: number,
  centralHeaderOffset: number
): Promise<void> {
  const localBytes = 30 + path.length + data.byteLength;
  const centralBytes = 46 + path.length;
  const encoded = await ZipWriter.encode(
    {[path]: data},
    {
      jszip: {
        compression: 'STORE',
        streamFiles: false,
        platform: 'DOS',
        date: new Date('1980-01-01T00:00:00Z')
      }
    }
  );
  if (encoded.byteLength !== localBytes + centralBytes + 22) {
    throw new Error('Unexpected indexed ZIP layout');
  }
  archive.set(new Uint8Array(encoded, 0, localBytes), localHeaderOffset);
  archive.set(new Uint8Array(encoded, localBytes, centralBytes), centralHeaderOffset);
  new DataView(archive.buffer).setUint32(centralHeaderOffset + 42, localHeaderOffset, true);
}

/** Compares MD5 values as two little-endian unsigned 64-bit integers, per the indexed archive specifications. */
function compareIndexEntries(left: DataView, right: DataView): number {
  for (const offset of [0, 8]) {
    const leftValue = left.getBigUint64(offset, true);
    const rightValue = right.getBigUint64(offset, true);
    if (leftValue !== rightValue) return leftValue < rightValue ? -1 : 1;
  }
  return 0;
}

/** Rejects paths whose bytes or ZIP layout would differ from the measured ASCII layout. */
function validatePath(path: string): void {
  if (
    path.length > 0xffff ||
    /[^\x20-\x7e]/.test(path) ||
    path.includes('\\') ||
    path.split('/').some(segment => !segment || segment === '.' || segment === '..')
  ) {
    throw new TypeError('Indexed ZIP requires canonical relative ASCII paths');
  }
}
