// loaders.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import {CRC32Hash, MD5Hash} from '@loaders.gl/crypto';
import {ZipWriter} from './zip-writer';

/** Already encoded resources. Inputs must remain unchanged while packaging. */
export type IndexedZipFiles = Readonly<Record<string, ArrayBuffer | Blob>>;

/** Configuration for a deterministic STORE ZIP32 with a final MD5 path/offset index. */
export interface IndexedZipOptions {
  /** Canonical ASCII, nonnumeric name for the generated final index entry. */
  readonly indexPath: string;
  /** Maximum final archive bytes, including headers/index; not a peak-memory limit. */
  readonly maxArchiveBytes: number;
  /** Hash lowercase paths for SLPK; retain case-sensitive paths for 3TZ by default. */
  readonly lowercasePaths?: boolean;
  /** Cooperative cancellation between block reads and header encodes; not an interrupt for either. */
  readonly signal?: AbortSignal;
}

/** Maximum temporary payload read/copy per block; caller inputs and index metadata are retained. */
const RESOURCE_CHUNK_BYTES = 64 * 1024;

/** Largest supported archive, below the ZIP64 sentinel. */
const MAX_ARCHIVE_BYTES = 0xfffffffe;

/**
 * Encodes a bounded, deterministic indexed ZIP32 from immutable ArrayBuffers or Blobs.
 * Validates/measures all entries before reading Blobs; hashes canonical ASCII resource paths.
 * Reads resource payloads in bounded blocks into the final buffer, with a checksum pass before each entry.
 * Uses populated local headers, no compression/descriptors/comments, and a fixed timestamp.
 * Cancellation is checked between block reads/encodes; use worker termination to interrupt active work.
 * @param files - Already authored resources, excluding the index generated by this encoder.
 * @param options - Index naming/hash profile and maximum complete archive size.
 * @returns ZIP bytes with the final 24-byte-per-resource MD5/offset index.
 */
export async function encodeIndexedZip(
  files: IndexedZipFiles,
  options: IndexedZipOptions
): Promise<ArrayBuffer> {
  const layout = prepareArchiveLayout(files, options);
  const archive = new Uint8Array(layout.archiveBytes);
  let offset = 0;
  for await (const chunk of encodeArchiveChunks(layout)) {
    archive.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return archive.buffer;
}

/**
 * Yields deterministic indexed ZIP32 chunks with consumer-controlled backpressure.
 * All paths and the complete archive budget are checked on the first pull, before Blob reads
 * or output. Reads/copies payloads in blocks of at most 64 KiB, retaining inputs and index/central
 * metadata without allocating a complete entry or archive buffer. A checksum pass reads each
 * resource before its populated local header; a second pass yields payload blocks on demand.
 * Chunks are byte views; consumers must respect their offsets and lengths. Inputs must stay unchanged. Stop iteration to prevent subsequent reads/encodes.
 * Cancellation is cooperative; callers own discarding partial output and storage finalization.
 * @param files - Already authored resources, excluding the generated index.
 * @param options - Index profile, complete output-size budget, and optional cancellation signal.
 * @returns Local entries followed by the central directory and ZIP end record.
 */
export async function* encodeIndexedZipInBatches(
  files: IndexedZipFiles,
  options: IndexedZipOptions
): AsyncIterable<Uint8Array<ArrayBuffer>> {
  yield* encodeArchiveChunks(prepareArchiveLayout(files, options));
}

/** Captures immutable resource descriptors and validates the complete ZIP32 layout before I/O. */
function prepareArchiveLayout(files: IndexedZipFiles, options: IndexedZipOptions) {
  const {maxArchiveBytes, indexPath, lowercasePaths = false, signal} = options;
  signal?.throwIfAborted();
  validatePath(indexPath);
  if (/^\d+$/.test(indexPath)) {
    throw new TypeError('Indexed ZIP index path must be nonnumeric to remain the final entry');
  }
  if (!Number.isSafeInteger(maxArchiveBytes) || maxArchiveBytes < 0) {
    throw new RangeError('Indexed ZIP archive byte limit must be a non-negative safe integer');
  }
  // Integer-like object keys follow ECMAScript enumeration order in JSZip as well.
  const paths = Object.keys(
    Object.fromEntries(
      Object.keys(files)
        .sort()
        .map(path => [path, true])
    )
  );
  if (paths.length >= 0xfffe) {
    throw new RangeError('Indexed ZIP requires fewer than 65534 resource files');
  }
  const canonicalPaths = paths.map(path => (lowercasePaths ? path.toLowerCase() : path));
  if (new Set(canonicalPaths).size !== paths.length) {
    throw new TypeError('Indexed ZIP contains duplicate canonical paths');
  }
  const resources = paths.map(path => {
    validatePath(path);
    if (
      (lowercasePaths ? path.toLowerCase() : path) ===
      (lowercasePaths ? indexPath.toLowerCase() : indexPath)
    ) {
      throw new TypeError('Indexed ZIP resource uses the reserved index path');
    }
    const data = files[path];
    const byteLength =
      data instanceof ArrayBuffer
        ? (Object.getOwnPropertyDescriptor(ArrayBuffer.prototype, 'byteLength')!.get!.call(
            data
          ) as number)
        : (Object.getOwnPropertyDescriptor(Blob.prototype, 'size')!.get!.call(data) as number);
    return {path, data, byteLength};
  });
  // ZIP32: EOCD + local/central headers + both copies of each ASCII path + index payload.
  const archiveBytes = resources.reduce(
    (total, resource) => total + 76 + 2 * resource.path.length + resource.byteLength,
    22 + 76 + 2 * indexPath.length + 24 * resources.length
  );
  if (archiveBytes > Math.min(maxArchiveBytes, MAX_ARCHIVE_BYTES)) {
    throw new RangeError('Indexed ZIP archive exceeds the configured byte limit or ZIP32 capacity');
  }

  return {resources, archiveBytes, indexPath, lowercasePaths, signal};
}

/** Serializes measured entries lazily, retaining only the index and central-directory records. */
async function* encodeArchiveChunks(
  layout: ReturnType<typeof prepareArchiveLayout>
): AsyncIterable<Uint8Array<ArrayBuffer>> {
  const {resources, archiveBytes, indexPath, lowercasePaths, signal} = layout;
  const entries: DataView[] = [];
  const centralHeaders: Uint8Array<ArrayBuffer>[] = [];
  const hash = new MD5Hash();
  let localHeaderOffset = 0;
  for (const resource of resources) {
    signal?.throwIfAborted();
    const checksum = await checksumResource(resource, signal);
    signal?.throwIfAborted();
    const digest = await hash.hash(
      new TextEncoder().encode(lowercasePaths ? resource.path.toLowerCase() : resource.path).buffer,
      'hex'
    );
    const entry = new DataView(new ArrayBuffer(24));
    for (let index = 0; index < 16; index++) {
      entry.setUint8(index, Number.parseInt(digest.slice(index * 2, index * 2 + 2), 16));
    }
    entry.setBigUint64(16, BigInt(localHeaderOffset), true);
    entries.push(entry);
    signal?.throwIfAborted();
    assertResourceSize(resource);
    const headers = await encodeEntryHeaders(
      resource.path,
      resource.byteLength,
      checksum,
      localHeaderOffset
    );
    signal?.throwIfAborted();
    assertResourceSize(resource);
    centralHeaders.push(headers.centralHeader);
    localHeaderOffset += headers.localHeader.byteLength + resource.byteLength;
    yield headers.localHeader;
    for await (const block of readResourceBlocks(resource, signal)) yield new Uint8Array(block);
  }
  entries.sort(compareIndexEntries);
  const indexData = new Uint8Array(24 * entries.length);
  entries.forEach((entry, index) => indexData.set(new Uint8Array(entry.buffer), index * 24));
  signal?.throwIfAborted();
  const indexResource = {data: indexData.buffer, byteLength: indexData.byteLength};
  const indexChecksum = await checksumResource(indexResource, signal);
  const indexHeaders = await encodeEntryHeaders(
    indexPath,
    indexData.byteLength,
    indexChecksum,
    localHeaderOffset
  );
  signal?.throwIfAborted();
  centralHeaders.push(indexHeaders.centralHeader);
  const centralDirectoryOffset =
    localHeaderOffset + indexHeaders.localHeader.byteLength + indexData.byteLength;
  yield indexHeaders.localHeader;
  for await (const block of readResourceBlocks(indexResource, signal)) yield new Uint8Array(block);
  for (const centralHeader of centralHeaders) {
    signal?.throwIfAborted();
    yield centralHeader;
  }
  signal?.throwIfAborted();
  // ZIP32 end-of-central-directory record; disk numbers and comment length remain zero.
  const endOfCentralDirectory = new DataView(new ArrayBuffer(22));
  endOfCentralDirectory.setUint32(0, 0x06054b50, true);
  endOfCentralDirectory.setUint16(8, resources.length + 1, true);
  endOfCentralDirectory.setUint16(10, resources.length + 1, true);
  endOfCentralDirectory.setUint32(12, archiveBytes - 22 - centralDirectoryOffset, true);
  endOfCentralDirectory.setUint32(16, centralDirectoryOffset, true);
  yield new Uint8Array(endOfCentralDirectory.buffer);
  signal?.throwIfAborted();
}

/** Captured resource size shared by the checksum and payload passes. */
interface ZipResource {
  /** Immutable caller-owned input, or generated index bytes. */
  readonly data: ArrayBuffer | Blob;
  /** Native byte size measured before any reads or output. */
  readonly byteLength: number;
}

/** Reads/copies one bounded block at a time, checking cancellation and captured sizes. */
async function* readResourceBlocks(
  resource: ZipResource,
  signal?: AbortSignal
): AsyncIterable<ArrayBuffer> {
  signal?.throwIfAborted();
  assertResourceSize(resource);
  for (let offset = 0; offset < resource.byteLength; offset += RESOURCE_CHUNK_BYTES) {
    signal?.throwIfAborted();
    assertResourceSize(resource);
    const end = Math.min(offset + RESOURCE_CHUNK_BYTES, resource.byteLength);
    const block =
      resource.data instanceof ArrayBuffer
        ? ArrayBuffer.prototype.slice.call(resource.data, offset, end)
        : await Blob.prototype.arrayBuffer.call(
            Blob.prototype.slice.call(resource.data, offset, end)
          );
    signal?.throwIfAborted();
    if (block.byteLength !== end - offset) {
      throw new TypeError('Indexed ZIP resource size changed during packaging');
    }
    yield block;
  }
  signal?.throwIfAborted();
}

/** Rejects ArrayBuffer detachment/resizing across asynchronous reads or header encoding. */
function assertResourceSize(resource: ZipResource): void {
  if (resource.data instanceof ArrayBuffer && resource.data.byteLength !== resource.byteLength) {
    throw new TypeError('Indexed ZIP resource size changed during packaging');
  }
}

/** Calculates CRC-32 incrementally without retaining the checksum pass's payload blocks. */
async function checksumResource(resource: ZipResource, signal?: AbortSignal): Promise<number> {
  let checksum = 0;
  const hash = new CRC32Hash({
    crypto: {
      /** Captures the final checksum after all input blocks have been consumed. */
      onEnd: (result: {/** Hex-encoded CRC-32 digest. */ hash: string}) => {
        checksum = Number.parseInt(result.hash, 16);
      }
    }
  });
  for await (const _block of hash.hashBatches(readResourceBlocks(resource, signal), 'hex')) {
    signal?.throwIfAborted();
  }
  return checksum;
}

/** Reuses the deterministic STORE header layout without passing payload bytes to JSZip. */
async function encodeEntryHeaders(
  path: string,
  byteLength: number,
  checksum: number,
  localHeaderOffset: number
): Promise<{
  /** Populated local header and ASCII resource name. */
  readonly localHeader: Uint8Array<ArrayBuffer>;
  /** Independent central header, safe when the local header's buffer is transferred. */
  readonly centralHeader: Uint8Array<ArrayBuffer>;
}> {
  const localBytes = 30 + path.length;
  const centralBytes = 46 + path.length;
  const encoded = await ZipWriter.encode(
    {[path]: new ArrayBuffer(0)},
    {
      jszip: {
        compression: 'STORE',
        streamFiles: false,
        platform: 'DOS',
        date: new Date('1980-01-01T00:00:00Z')
      }
    }
  );
  if (encoded.byteLength !== localBytes + centralBytes + 22) {
    throw new Error('Unexpected indexed ZIP layout');
  }
  const header = new DataView(encoded);
  header.setUint32(14, checksum, true);
  header.setUint32(18, byteLength, true);
  header.setUint32(22, byteLength, true);
  header.setUint32(localBytes + 16, checksum, true);
  header.setUint32(localBytes + 20, byteLength, true);
  header.setUint32(localBytes + 24, byteLength, true);
  header.setUint32(localBytes + 42, localHeaderOffset, true);
  return {
    localHeader: new Uint8Array(encoded, 0, localBytes),
    centralHeader: new Uint8Array(encoded.slice(localBytes, -22))
  };
}

/** Compares MD5 values as two little-endian unsigned 64-bit integers, per the indexed archive specifications. */
function compareIndexEntries(left: DataView, right: DataView): number {
  for (const offset of [0, 8]) {
    const leftValue = left.getBigUint64(offset, true);
    const rightValue = right.getBigUint64(offset, true);
    if (leftValue !== rightValue) return leftValue < rightValue ? -1 : 1;
  }
  return 0;
}

/** Rejects paths whose bytes or ZIP layout would differ from the measured ASCII layout. */
function validatePath(path: string): void {
  if (
    path.length > 0xffff ||
    /[^\x20-\x7e]/.test(path) ||
    path.includes('\\') ||
    path.split('/').some(segment => !segment || segment === '.' || segment === '..')
  ) {
    throw new TypeError('Indexed ZIP requires canonical relative ASCII paths');
  }
}
