nodeLinker: node-modules
logFilters:
  - code: YN0057
    pattern: '*Resolutions field will be ignored*'
    level: discard
  - code: YN0060
    pattern: '*@loaders.gl/core is listed by your project with version 4.4.0*'
    level: discard
  - code: YN0060
    pattern: '*@types/react is listed by your project with version 19.2.14*'
    level: discard
  - code: YN0060
    pattern: '*react is listed by your project with version 19.2.5*'
    level: discard
  - code: YN0060
    pattern: '*react-dom is listed by your project with version 19.2.5*'
    level: discard
  - code: YN0002
    pattern: '*doesn''t provide @loaders.gl/core*'
    level: discard
  - code: YN0002
    pattern: '*doesn''t provide ol*'
    level: discard
  - code: YN0002
    pattern: '*doesn''t provide ws*'
    level: discard
  - code: YN0086
    pattern: '*Some peer dependencies are incorrectly met*'
    level: discard
