approvedGitRepositories:
  - "**"

enableScripts: true

logFilters:
  - code: YN0057
    level: discard
    pattern: "*Resolutions field will be ignored*"
  - code: YN0060
    level: discard
    pattern: "*@loaders.gl/core is listed by your project with version 4.4.0*"
  - code: YN0060
    level: discard
    pattern: "*@types/react is listed by your project with version 19.2.14*"
  - code: YN0060
    level: discard
    pattern: "*react is listed by your project with version 19.2.5*"
  - code: YN0060
    level: discard
    pattern: "*react-dom is listed by your project with version 19.2.5*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @loaders.gl/core*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide ol*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide ws*"
  - code: YN0086
    level: discard
    pattern: "*Some peer dependencies are incorrectly met*"

nodeLinker: node-modules
