/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.2
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
import * as thrift from 'thrift';
import * as Encoding from './Encoding';
export interface IDictionaryPageHeaderArgs {
  num_values: number;
  encoding: Encoding.Encoding;
  is_sorted?: boolean;
}
export class DictionaryPageHeader {
  public num_values: number;
  public encoding: Encoding.Encoding;
  public is_sorted?: boolean;
  constructor(args: IDictionaryPageHeaderArgs) {
    if (args != null && args.num_values != null) {
      this.num_values = args.num_values;
    } else {
      throw new thrift.Thrift.TProtocolException(
        thrift.Thrift.TProtocolExceptionType.UNKNOWN,
        'Required field[num_values] is unset!'
      );
    }
    if (args != null && args.encoding != null) {
      this.encoding = args.encoding;
    } else {
      throw new thrift.Thrift.TProtocolException(
        thrift.Thrift.TProtocolExceptionType.UNKNOWN,
        'Required field[encoding] is unset!'
      );
    }
    if (args != null && args.is_sorted != null) {
      this.is_sorted = args.is_sorted;
    }
  }
  public write(output: thrift.TProtocol): void {
    output.writeStructBegin('DictionaryPageHeader');
    if (this.num_values != null) {
      output.writeFieldBegin('num_values', thrift.Thrift.Type.I32, 1);
      output.writeI32(this.num_values);
      output.writeFieldEnd();
    }
    if (this.encoding != null) {
      output.writeFieldBegin('encoding', thrift.Thrift.Type.I32, 2);
      output.writeI32(this.encoding);
      output.writeFieldEnd();
    }
    if (this.is_sorted != null) {
      output.writeFieldBegin('is_sorted', thrift.Thrift.Type.BOOL, 3);
      output.writeBool(this.is_sorted);
      output.writeFieldEnd();
    }
    output.writeFieldStop();
    output.writeStructEnd();
    return;
  }
  public static read(input: thrift.TProtocol): DictionaryPageHeader {
    input.readStructBegin();
    let _args: any = {};
    while (true) {
      const ret: thrift.TField = input.readFieldBegin();
      const fieldType: thrift.Thrift.Type = ret.ftype;
      const fieldId: number = ret.fid;
      if (fieldType === thrift.Thrift.Type.STOP) {
        break;
      }
      switch (fieldId) {
        case 1:
          if (fieldType === thrift.Thrift.Type.I32) {
            const value_1: number = input.readI32();
            _args.num_values = value_1;
          } else {
            input.skip(fieldType);
          }
          break;
        case 2:
          if (fieldType === thrift.Thrift.Type.I32) {
            const value_2: Encoding.Encoding = input.readI32();
            _args.encoding = value_2;
          } else {
            input.skip(fieldType);
          }
          break;
        case 3:
          if (fieldType === thrift.Thrift.Type.BOOL) {
            const value_3: boolean = input.readBool();
            _args.is_sorted = value_3;
          } else {
            input.skip(fieldType);
          }
          break;
        default: {
          input.skip(fieldType);
        }
      }
      input.readFieldEnd();
    }
    input.readStructEnd();
    if (_args.num_values !== undefined && _args.encoding !== undefined) {
      return new DictionaryPageHeader(_args);
    } else {
      throw new thrift.Thrift.TProtocolException(
        thrift.Thrift.TProtocolExceptionType.UNKNOWN,
        'Unable to read DictionaryPageHeader from input'
      );
    }
  }
}
