// loaders.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import type {WriterOptions, WriterWithEncoder} from '@loaders.gl/loader-utils';
import type {Mesh, MeshArrowTable, MeshAttribute} from '@loaders.gl/schema';
import {convertMeshToTable, convertTableToMesh} from '@loaders.gl/schema-utils';
import {PCDFormat} from './pcd-format';

// __VERSION__ is injected by babel-plugin-version-inline
// @ts-ignore TS2304: Cannot find name '__VERSION__'.
const VERSION = typeof __VERSION__ !== 'undefined' ? __VERSION__ : 'latest';

/** Options for `PCDWriter`. */
export type PCDWriterOptions = WriterOptions & {
  /** Reserved for future PCD writer options. */
  pcd?: Record<string, never>;
};

/**
 * Writer for the PCD point cloud format.
 */
export const PCDWriter = {
  ...PCDFormat,
  dataType: null as unknown as Mesh | MeshArrowTable,
  batchType: null as never,
  version: VERSION,
  options: {
    pcd: {}
  },
  text: true,
  encode: async (data, options) => encodePCDSync(data, options),
  encodeSync: encodePCDSync,
  encodeTextSync: encodePCD
} as const satisfies WriterWithEncoder<Mesh | MeshArrowTable, never, PCDWriterOptions>;

/** Encode mesh category data as PCD bytes. */
function encodePCDSync(data: Mesh | MeshArrowTable, options?: PCDWriterOptions): ArrayBuffer {
  const text = encodePCD(data, options);
  return new TextEncoder().encode(text).buffer;
}

/** Encode mesh category data as ASCII PCD text. */
function encodePCD(data: Mesh | MeshArrowTable, options?: PCDWriterOptions): string {
  const mesh = convertTableToMesh(normalizeMeshArrowTable(data));
  const positionAttribute = getRequiredAttribute(mesh, 'POSITION');
  const normalAttribute = mesh.attributes.NORMAL;
  const colorAttribute = mesh.attributes.COLOR_0;
  const vertexCount = positionAttribute.value.length / positionAttribute.size;
  const fieldNames = ['x', 'y', 'z'];
  const fieldSizes = ['4', '4', '4'];
  const fieldTypes = ['F', 'F', 'F'];
  const fieldCounts = ['1', '1', '1'];

  if (normalAttribute) {
    fieldNames.push('normal_x', 'normal_y', 'normal_z');
    fieldSizes.push('4', '4', '4');
    fieldTypes.push('F', 'F', 'F');
    fieldCounts.push('1', '1', '1');
  }

  if (colorAttribute) {
    fieldNames.push('rgb');
    fieldSizes.push('4');
    fieldTypes.push('F');
    fieldCounts.push('1');
  }

  const lines = [
    '# .PCD v0.7 - Point Cloud Data file generated by loaders.gl',
    'VERSION 0.7',
    `FIELDS ${fieldNames.join(' ')}`,
    `SIZE ${fieldSizes.join(' ')}`,
    `TYPE ${fieldTypes.join(' ')}`,
    `COUNT ${fieldCounts.join(' ')}`,
    `WIDTH ${vertexCount}`,
    'HEIGHT 1',
    'VIEWPOINT 0 0 0 1 0 0 0',
    `POINTS ${vertexCount}`,
    'DATA ascii'
  ];

  for (let vertexIndex = 0; vertexIndex < vertexCount; vertexIndex++) {
    const row = [
      getComponent(positionAttribute, vertexIndex, 0),
      getComponent(positionAttribute, vertexIndex, 1),
      getComponent(positionAttribute, vertexIndex, 2)
    ];

    if (normalAttribute) {
      row.push(
        getComponent(normalAttribute, vertexIndex, 0),
        getComponent(normalAttribute, vertexIndex, 1),
        getComponent(normalAttribute, vertexIndex, 2)
      );
    }

    if (colorAttribute) {
      row.push(getPackedRGB(colorAttribute, vertexIndex));
    }

    lines.push(row.join(' '));
  }

  return `${lines.join('\n')}\n`;
}

/** Return mesh data as a MeshArrowTable, converting plain Mesh data first. */
function normalizeMeshArrowTable(data: Mesh | MeshArrowTable): MeshArrowTable {
  if ('shape' in data && data.shape === 'arrow-table') {
    return data;
  }
  return convertMeshToTable(data as Mesh, 'arrow-table');
}

/** Return a required mesh attribute or throw a format-specific error. */
function getRequiredAttribute(mesh: Mesh, attributeName: string): MeshAttribute {
  const attribute = mesh.attributes[attributeName];
  if (!attribute) {
    throw new Error(`PCDWriter: ${attributeName} attribute is required`);
  }
  return attribute;
}

/** Return a single attribute component with 0 as the missing component fallback. */
function getComponent(
  attribute: MeshAttribute,
  vertexIndex: number,
  componentIndex: number
): number {
  return attribute.value[vertexIndex * attribute.size + componentIndex] || 0;
}

/** Return an RGB value packed into the PCD float convention. */
function getPackedRGB(attribute: MeshAttribute, vertexIndex: number): number {
  const bytes = new Uint8Array(4);
  bytes[0] = getColorByte(attribute, vertexIndex, 0);
  bytes[1] = getColorByte(attribute, vertexIndex, 1);
  bytes[2] = getColorByte(attribute, vertexIndex, 2);
  return new DataView(bytes.buffer).getFloat32(0, true);
}

/** Return one color component as an unsigned byte. */
function getColorByte(
  attribute: MeshAttribute,
  vertexIndex: number,
  componentIndex: number
): number {
  const value = getComponent(attribute, vertexIndex, componentIndex);
  const byteValue = attribute.normalized || value <= 1 ? value * 255 : value;
  return Math.max(0, Math.min(255, Math.round(byteValue)));
}
