// loaders.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import {z} from 'zod';

/** One vector layer declaration in raw TileJSON metadata. */
export interface TileJSONVectorLayer {
  /** Stable identifier used by vector-tile features. */
  id?: string;
  /** Human-readable layer description. */
  description?: string;
  /** Declared field names mapped to producer-specific field type names. */
  fields?: Record<string, string>;
  /** Minimum zoom at which the layer is available. */
  minzoom?: number;
  /** Maximum zoom at which the layer is available. */
  maxzoom?: number;
  /** Additional TileJSON layer properties are preserved verbatim. */
  [key: string]: unknown;
}

/** Statistics for one attribute in a raw Tilestats document. */
export interface TilestatsLayerAttribute {
  /** Attribute name. */
  attribute?: string;
  /** Producer-specific attribute type such as `string`, `number`, or `boolean`. */
  type?: string;
  /** Minimum numeric value observed for the attribute. */
  min?: number;
  /** Maximum numeric value observed for the attribute. */
  max?: number;
  /** Number of unique values observed for the attribute. */
  count?: number;
  /** Sample of unique values observed for the attribute. */
  values?: unknown[];
  /** Additional attribute statistics are preserved verbatim. */
  [key: string]: unknown;
}

/** Statistics for one vector layer in a raw Tilestats document. */
export interface TilestatsLayer {
  /** Vector layer identifier. */
  layer?: string;
  /** Total feature count for the layer. */
  count?: number;
  /** Dominant geometry type in the layer. */
  geometry?: string;
  /** Number of distinct attributes described for the layer. */
  attributeCount?: number;
  /** Attribute statistics for the layer. */
  attributes?: TilestatsLayerAttribute[];
  /** Additional layer statistics are preserved verbatim. */
  [key: string]: unknown;
}

/** Raw Tilestats metadata embedded in or accompanying TileJSON. */
export interface Tilestats {
  /** Number of layers represented by the metadata. */
  layerCount?: number;
  /** Per-layer statistics. */
  layers?: TilestatsLayer[];
  /** Additional Tilestats properties are preserved verbatim. */
  [key: string]: unknown;
}

/**
 * Raw TileJSON metadata accepted by loaders.gl before normalization.
 *
 * Known properties are optional because loaders.gl also accepts partial TileJSON-like metadata
 * embedded in PMTiles and generated by tools such as Tippecanoe.
 */
export interface TileJSONMetadata {
  /** TileJSON specification version. */
  tilejson?: string;
  /** Human-readable tileset name. */
  name?: string;
  /** Human-readable tileset description. */
  description?: string;
  /** Producer-specific tileset version. */
  version?: string;
  /** Tile indexing scheme. */
  scheme?: 'xyz' | 'tms';
  /** Tile URL templates. */
  tiles?: string[];
  /** Geographic bounds as an array or comma-separated string. */
  bounds?: number[] | string;
  /** Tippecanoe bounds adjusted to avoid crossing the antimeridian. */
  antimeridian_adjusted_bounds?: number[] | string;
  /** Default map center as an array or comma-separated string. */
  center?: number[] | string;
  /** Minimum zoom, optionally encoded as a string by metadata producers. */
  minzoom?: number | string;
  /** Maximum zoom, optionally encoded as a string by metadata producers. */
  maxzoom?: number | string;
  /** HTML attribution for the tileset. */
  attribution?: string;
  /** HTML legend for the tileset. */
  legend?: string;
  /** Vector layer declarations. */
  vector_layers?: TileJSONVectorLayer[];
  /** Inline Tilestats metadata. */
  tilestats?: Tilestats;
  /** Nested JSON metadata encoded as a string. */
  json?: string;
  /** Generating application. */
  generator?: string;
  /** Command-line or application options used by the generator. */
  generator_options?: string;
  /** Additional TileJSON properties are preserved verbatim. */
  [key: string]: unknown;
}

/** Zod schema for one raw TileJSON vector layer. */
export const TileJSONVectorLayerSchema = z
  .object({
    id: z.string().optional(),
    description: z.string().optional(),
    fields: z.record(z.string(), z.string()).optional(),
    minzoom: z.number().optional(),
    maxzoom: z.number().optional()
  })
  .passthrough() satisfies z.ZodType<TileJSONVectorLayer>;

/** Zod schema for one raw Tilestats attribute. */
export const TilestatsLayerAttributeSchema = z
  .object({
    attribute: z.string().optional(),
    type: z.string().optional(),
    min: z.number().optional(),
    max: z.number().optional(),
    count: z.number().nonnegative().optional(),
    values: z.array(z.unknown()).optional()
  })
  .passthrough() satisfies z.ZodType<TilestatsLayerAttribute>;

/** Zod schema for one raw Tilestats layer. */
export const TilestatsLayerSchema = z
  .object({
    layer: z.string().optional(),
    count: z.number().nonnegative().optional(),
    geometry: z.string().optional(),
    attributeCount: z.number().nonnegative().optional(),
    attributes: z.array(TilestatsLayerAttributeSchema).optional()
  })
  .passthrough() satisfies z.ZodType<TilestatsLayer>;

/** Zod schema for raw Tilestats metadata. */
export const TilestatsSchema = z
  .object({
    layerCount: z.number().nonnegative().optional(),
    layers: z.array(TilestatsLayerSchema).optional()
  })
  .passthrough() satisfies z.ZodType<Tilestats>;

const numberArrayOrStringSchema = z.union([z.array(z.number()), z.string()]);
const numberOrStringSchema = z.union([z.number(), z.string()]);

/** Zod schema for raw TileJSON and compatible partial metadata accepted by loaders.gl. */
export const TileJSONMetadataSchema = z
  .object({
    tilejson: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    version: z.string().optional(),
    scheme: z.enum(['xyz', 'tms']).optional(),
    tiles: z.array(z.string()).optional(),
    bounds: numberArrayOrStringSchema.optional(),
    antimeridian_adjusted_bounds: numberArrayOrStringSchema.optional(),
    center: numberArrayOrStringSchema.optional(),
    minzoom: numberOrStringSchema.optional(),
    maxzoom: numberOrStringSchema.optional(),
    attribution: z.string().optional(),
    legend: z.string().optional(),
    vector_layers: z.array(TileJSONVectorLayerSchema).optional(),
    tilestats: TilestatsSchema.optional(),
    json: z.string().optional(),
    generator: z.string().optional(),
    generator_options: z.string().optional()
  })
  .passthrough() satisfies z.ZodType<TileJSONMetadata>;
