// loaders.gl
// SPDX-License-Identifier: MIT
// Copyright (c) vis.gl contributors

import type {WriterOptions, WriterWithEncoder} from '@loaders.gl/loader-utils';
import type {Mesh, MeshArrowTable, MeshAttribute} from '@loaders.gl/schema';
import {convertMeshToTable, convertTableToMesh} from '@loaders.gl/schema-utils';
import {PLYFormat} from './ply-format';

// __VERSION__ is injected by babel-plugin-version-inline
// @ts-ignore TS2304: Cannot find name '__VERSION__'.
const VERSION = typeof __VERSION__ !== 'undefined' ? __VERSION__ : 'latest';

/** Options for `PLYWriter`. */
export type PLYWriterOptions = WriterOptions & {
  /** Reserved for future PLY writer options. */
  ply?: Record<string, never>;
};

/**
 * Writer for the PLY geometry format.
 */
export const PLYWriter = {
  ...PLYFormat,
  dataType: null as unknown as Mesh | MeshArrowTable,
  batchType: null as never,
  version: VERSION,
  options: {
    ply: {}
  },
  text: true,
  encode: async (data, options) => encodePLYSync(data, options),
  encodeSync: encodePLYSync,
  encodeTextSync: encodePLY
} as const satisfies WriterWithEncoder<Mesh | MeshArrowTable, never, PLYWriterOptions>;

/** Encode mesh category data as PLY bytes. */
function encodePLYSync(data: Mesh | MeshArrowTable, options?: PLYWriterOptions): ArrayBuffer {
  const text = encodePLY(data, options);
  return new TextEncoder().encode(text).buffer;
}

/** Encode mesh category data as ASCII PLY text. */
function encodePLY(data: Mesh | MeshArrowTable, options?: PLYWriterOptions): string {
  const mesh = convertTableToMesh(normalizeMeshArrowTable(data));
  const positionAttribute = getRequiredAttribute(mesh, 'POSITION');
  const normalAttribute = mesh.attributes.NORMAL;
  const textureCoordinateAttribute = mesh.attributes.TEXCOORD_0;
  const colorAttribute = mesh.attributes.COLOR_0;
  const customScalarAttributes = getCustomScalarAttributes(mesh);
  const vertexCount = positionAttribute.value.length / positionAttribute.size;
  const triangleIndices = getTriangleIndices(mesh, vertexCount);
  const header = getPLYHeader(
    vertexCount,
    triangleIndices.length / 3,
    Boolean(normalAttribute),
    Boolean(textureCoordinateAttribute),
    Boolean(colorAttribute),
    customScalarAttributes
  );
  const rows: string[] = [];

  for (let vertexIndex = 0; vertexIndex < vertexCount; vertexIndex++) {
    const row = [
      getComponent(positionAttribute, vertexIndex, 0),
      getComponent(positionAttribute, vertexIndex, 1),
      getComponent(positionAttribute, vertexIndex, 2)
    ];

    if (normalAttribute) {
      row.push(
        getComponent(normalAttribute, vertexIndex, 0),
        getComponent(normalAttribute, vertexIndex, 1),
        getComponent(normalAttribute, vertexIndex, 2)
      );
    }

    if (textureCoordinateAttribute) {
      row.push(
        getComponent(textureCoordinateAttribute, vertexIndex, 0),
        getComponent(textureCoordinateAttribute, vertexIndex, 1)
      );
    }

    if (colorAttribute) {
      row.push(
        getColorByte(colorAttribute, vertexIndex, 0),
        getColorByte(colorAttribute, vertexIndex, 1),
        getColorByte(colorAttribute, vertexIndex, 2)
      );
    }

    for (const [, attribute] of customScalarAttributes) {
      row.push(getComponent(attribute, vertexIndex, 0));
    }

    rows.push(row.join(' '));
  }

  for (let triangleIndex = 0; triangleIndex < triangleIndices.length; triangleIndex += 3) {
    rows.push(
      `3 ${triangleIndices[triangleIndex]} ${triangleIndices[triangleIndex + 1]} ${
        triangleIndices[triangleIndex + 2]
      }`
    );
  }

  return `${header.concat(rows).join('\n')}\n`;
}

/** Return mesh data as a MeshArrowTable, converting plain Mesh data first. */
function normalizeMeshArrowTable(data: Mesh | MeshArrowTable): MeshArrowTable {
  if ('shape' in data && data.shape === 'arrow-table') {
    return data;
  }
  return convertMeshToTable(data as Mesh, 'arrow-table');
}

/** Return a required mesh attribute or throw a format-specific error. */
function getRequiredAttribute(mesh: Mesh, attributeName: string): MeshAttribute {
  const attribute = mesh.attributes[attributeName];
  if (!attribute) {
    throw new Error(`PLYWriter: ${attributeName} attribute is required`);
  }
  return attribute;
}

/** Return the ASCII PLY header lines. */
function getPLYHeader(
  vertexCount: number,
  faceCount: number,
  hasNormals: boolean,
  hasTextureCoordinates: boolean,
  hasColors: boolean,
  customScalarAttributes: [string, MeshAttribute][]
): string[] {
  const header = [
    'ply',
    'format ascii 1.0',
    'comment generated by loaders.gl',
    `element vertex ${vertexCount}`,
    'property float x',
    'property float y',
    'property float z'
  ];

  if (hasNormals) {
    header.push('property float nx', 'property float ny', 'property float nz');
  }

  if (hasTextureCoordinates) {
    header.push('property float s', 'property float t');
  }

  if (hasColors) {
    header.push('property uchar red', 'property uchar green', 'property uchar blue');
  }

  for (const [attributeName] of customScalarAttributes) {
    header.push(`property float ${attributeName}`);
  }

  if (faceCount > 0) {
    header.push(`element face ${faceCount}`, 'property list uchar int vertex_indices');
  }

  header.push('end_header');
  return header;
}

/** Return additional one-component attributes that can be represented as scalar PLY properties. */
function getCustomScalarAttributes(mesh: Mesh): [string, MeshAttribute][] {
  const reservedAttributeNames = new Set(['POSITION', 'NORMAL', 'TEXCOORD_0', 'COLOR_0']);
  return Object.entries(mesh.attributes).filter(
    ([attributeName, attribute]) =>
      !reservedAttributeNames.has(attributeName) && attribute.size === 1
  );
}

/** Return a single attribute component with 0 as the missing component fallback. */
function getComponent(
  attribute: MeshAttribute,
  vertexIndex: number,
  componentIndex: number
): number {
  return attribute.value[vertexIndex * attribute.size + componentIndex] || 0;
}

/** Return one color component as an unsigned byte. */
function getColorByte(
  attribute: MeshAttribute,
  vertexIndex: number,
  componentIndex: number
): number {
  const value = getComponent(attribute, vertexIndex, componentIndex);
  const byteValue = attribute.normalized || value <= 1 ? value * 255 : value;
  return Math.max(0, Math.min(255, Math.round(byteValue)));
}

/** Return triangle indices for indexed or sequential triangle-list meshes. */
function getTriangleIndices(mesh: Mesh, vertexCount: number): number[] {
  if (mesh.indices?.value?.length) {
    return Array.from(mesh.indices.value);
  }

  if (mesh.mode !== 4 && mesh.topology !== 'triangle-list') {
    return [];
  }

  const triangleIndices: number[] = [];
  for (let vertexIndex = 0; vertexIndex + 2 < vertexCount; vertexIndex += 3) {
    triangleIndices.push(vertexIndex, vertexIndex + 1, vertexIndex + 2);
  }
  return triangleIndices;
}
